### ISSUE TITLE
Review #1 - El diseño se rompe en modo desktop.

### ISSUE THREAD

**Issue by FacundoEG** [alexbal12/game-ppt#1]
Hola Alex! como estas? estuve probando la webapp y hay algunas cositas relacionadas al diseño que me gustaría mostrarte:

Primero que todo, en la parte de /instructions en resolución desktop, noto como el div "page-b" se rompe saliendose del viewport, lo revise y al parecer el problema es en el gap que tiene para separar los elementos que lo "empuja" por afuera del root.

![image](https://user-images.githubusercontent.com/79592789/135780335-e7ac94be-1980-4401-905d-68f4d1982ce7.png)

Te podría sugerir que de ultima, pruebes de usar algunas de las propiedades de display:flex o (como justify-content: space-around, sin usar gap) o que uses un gap con porcentajes, para que se mantenga dentro de su propio espacio.

Después, me llama la atención que la pagina no tiene scroll al iniciar, pero al mostrar las jugadas de las manos y los resultados, vuelve a tener scroll (inclusive las manos se salen del viewport). También te sugeriría que revises eso, no es que este mal en si, pero se siente extraño que una parte este con scroll y la otra sin.

Para finalizar, noto que el div "page-d" en la parte de "/result" no llega a tomar toda la altura de la pantalla:

![image](https://user-images.githubusercontent.com/79592789/135780662-1994176a-879e-46bb-9576-9355337578a6.png)

Sacando esos detalles, en la parte del juego todo se desarrolla muy bien y los scores quedan guardados! así que en ese sentido te quedo muy bien el desafío.

Te pediría que revises esos detalles y mandes los cambios si?

Saludos!

**Comment by FerDR89** [comment]
Buenas Alex, 
Felicitaciones por llegas hasta acá.
La parte de mobile esta muy bien lograda pero la parte de desktop como indico Facu se rompe.
Ajústate esa parte de los media querie y volve a mandarlo que es un recontra aprobado!

**Comment by alexbalieiro** [comment]
muchas gracias chicos, ahí realicé algunas correcciones, espero que haya quedado mejor, reniego con esto de las pantallas siempre jeje, saludos

**Comment by FacundoEG** [comment]
Alex ahí lo chequie y quedo de 10! te cierro el issue porque ya solucionaste esto si?

Abrazos y nos vemos del otro lado!

**Comment by alexbalieiro** [comment]
muchas gracias por la devolución, nos estamos viendo, abrazo
